### PR TITLE
📝 Add Lisa Maria Moritz

### PR DESCRIPTION
**Pull request by McPringle**
Together with Eberhard Wolff Lisa is doing the Software Architektur TV podcast.

### CODE REVIEW

**Comment by scordio** [comment]
@marchof we might add support for two additional platforms related to podcasts: Apple and Spotify.

However, the table would require more space... what was the original purpose of the Handles column? Is it something we could sacrifice?

**Comment by marchof** [comment]
@scordio I personally sometimes use the handle column for "reverse looksup", also I remember many Java people more by their handle than their real name :)

If we want to add more platforms or links I don't think the table design scales well anyways. I'm not a UI expert but probably we have to move in a different direction like details pages, separate pages per platform etc.

**Comment by McPringle** [comment]
A possible solution could be to stick with a wide table (to keep it simple). Many people have a wide screen. But we can use CSS to hide some columns on smaller screens and use JavaScript to offer a column selector to the user. The table grows and grows, so a JavaScript based search would be more pleasant, too.

**Comment by marchof** [comment]
Sure, if someone with web skills jumps in...

**Comment by scordio** [comment]
I'll open a separate issue to discuss it further.

**Comment by McPringle** [comment]
> Sure, if someone with web skills jumps in...

I can try to contribute when we align on a solution.

**Pull request merged**
