### PR TITLE
Write handles consistently without leading @

### PR DESCRIPTION
**Pull request by marchof**
The leading @ is only used to make a reference to a user but not part of the user handle itself.

### CODE REVIEW

**Comment by marchof** [comment]
Hi @moelholm, can I remove the leading @s from the twitter and mastodon handles without completely breaking [javabubble@masto.ai](https://mastodon.social/@javabubble@masto.ai)?

**Comment by moelholm** [comment]
> Hi @moelholm, can I remove the leading @s from the twitter and mastodon handles without completely breaking [javabubble@masto.ai](https://mastodon.social/@javabubble@masto.ai)?

If it is removed from the JSON file you have then it will break the bot. But I can fix it so that it handles fediverse handles without leading @s. I can do it so that it it compatible before you merge this?

**Comment by moelholm** [comment]
@marchof bot updated. you can merge - no problems 😄

**Comment by marchof** [comment]
@moelholm That was quick, thanks!

**Pull request merged**
