### PR TITLE
Add individual profile links 

### PR DESCRIPTION
**Pull request by gsaslis**
With this list getting longer and longer, I was missing a way to individually follow people I am interested in, as opposed to the full list - or exploring profiles of people I didn't yet know before blindly following them.

This change should help with that

### CODE REVIEW

**Comment by marchof** [comment]
Hi @gsaslis nice idea! I have two questions though:

1) Have you tested @kabutz' CSV exporter script at `gen/GenerateImport.java` with this? Does it still work?
2) Maybe at this point we should move to a structured data format (json, yaml, csv...) and generate a HTML page

**Comment by kabutz** [comment]
My script should still work :-)

**Comment by marchof** [comment]
Not sure though whether the redundant information is a good way to maintain it. I would rather use a structured data format and generate a clickable/sortable/searcheable HTML page, CSV export etc. E.g. this yaml:

```
- name: "Heinz Kabutz"
  twitter: "@heinzkabutz"
  fediverse: "@HeinzKabutz@mastodon.social"
- name: "Yorgos Saslis"
  twitter: "@gsaslis"
  fediverse: "@yorgos_@mastodon.social"
```

But I propose to keep the existing format for now until incoming PRs cool down a bit.

**Comment by gsaslis** [comment]
I've merged in the latest changes from master and fixed the export script (which I had tried up until my previous commit). 

I still think this is a valuable usability improvement for this time when many folks are considering / trying out mastodon over twitter.

**Comment by gsaslis** [comment]
(but I obviously won't insist that this makes it in or anything.. was just trying to share a point of view from someone who didn't want to blindly follow everyone on this list - the move to mastodon is a good opportunity for a fresh start and a more focused timeline)

**Comment by marchof** [comment]
@gsaslis I completely agree with you about the idea. My point is that I currently have to fix every other PR regarding syntax and sorting. Therefore I would prefer to have the data base as simple as possible. Give me some days and we will have a clean data structure and a nice UI.

**Comment by gsaslis** [comment]
cool, that works for me ;) 🍻

**Pull request closed without merging**
