### PR TITLE
Add Edson Yanaga

### PR DESCRIPTION
**Pull request by yanaga**

### CODE REVIEW

**Comment by uweschaefer** [comment]
@yanaga Does this account post Japanese only content?

**Comment by yanaga** [comment]
I didn't post anything on Mastodon yet (I just joined). Unfortunately, I'm not fluent enough to post anything in Japanese. My posts are mainly in English, with a few occasional posts in Portuguese.

**Comment by marchof** [comment]
Please add to `README.md`. The file `followers.csv` was generated and has been removed from the source tree. Sorry for the inconvenience.

**Comment by uweschaefer** [comment]
@yanaga apologies, my fault. i confused the account with a Japanese one. 
I am having problems finding you on the instance, but that might be temporary. cheers.

**Comment by marchof** [comment]
Added with d465f5bbb3c2424ad2a8583f17c0d429daa897c7

**Pull request closed without merging**
